# Generated by Django 5.1.4 on 2025-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_attraction_image_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(blank=True, choices=[('Beach', 'Beach'), ('Forest', 'Forest'), ('Attraction', 'Attraction')], max_length=50, null=True),
        ),
    ]
