# Generated by Django 5.1.4 on 2025-01-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_destination_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='attraction',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.destination'),
        ),
    ]
