# Generated by Django 5.1.4 on 2025-01-12 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_remove_booking_attraction_booking_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
